// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5HzZWl53BjeCi5xtBqRG1CxhXyXImgE',
    appId: '1:515943770183:web:d99cf7e3a79a912a58e962',
    messagingSenderId: '515943770183',
    projectId: 'reddit-clone-bf04f',
    authDomain: 'reddit-clone-bf04f.firebaseapp.com',
    storageBucket: 'reddit-clone-bf04f.appspot.com',
    measurementId: 'G-R349V8C9Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Dx9K28KJTnimvITspvQJ8w-lRmkWccw',
    appId: '1:515943770183:android:07e9437bf1993e4358e962',
    messagingSenderId: '515943770183',
    projectId: 'reddit-clone-bf04f',
    storageBucket: 'reddit-clone-bf04f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFJEqD7fNwN-OHvPIP0AmtN6WmohpMg0',
    appId: '1:515943770183:ios:ce9251f422fb2eb358e962',
    messagingSenderId: '515943770183',
    projectId: 'reddit-clone-bf04f',
    storageBucket: 'reddit-clone-bf04f.appspot.com',
    androidClientId: '515943770183-uvuq8vm8q8d7u4rbi780a1pqc2hf17bj.apps.googleusercontent.com',
    iosClientId: '515943770183-fknimaike3qhqnts7npgg7i6kffcv9ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
